### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by steom** [kayrus/go-tun2socks#3]
Please can you provide Windows release for 32bit and 64bit?

**Comment by kayrus** [comment]
windows 64bit release is already available. as for 32bit, unfortunately travis-ci doesn't provide this architecture and I don't have enough time to develop proper cross-arch compilation workflow.

**Comment by steom** [comment]
It's a shame... So for 32bit we need to use this competitor project?
https://github.com/xjasonlyu/tun2socks
