### ISSUE TITLE
Udpgw support

### ISSUE THREAD

**Issue by mukswilly** [kayrus/go-tun2socks#4]
Hello, thanks for the good work. Is it possible to add support for udpgw?

**Comment by ghost** [comment]
@kayrus please add support for udpgw

**Comment by mukswilly** [comment]
@kayrus 
Pointers to such an implementation of this in go can be found at https://github.com/Psiphon-Labs/psiphon-tunnel-core/blob/6623cf49c57965266923d733a118dfd1aff52f9c/psiphon/server/udp.go and https://github.com/Psiphon-Labs/psiphon-tunnel-core/blob/6623cf49c57965266923d733a118dfd1aff52f9c/psiphon/server/server_test.go#L2188

**Comment by mukswilly** [comment]
If anyone is interested in udpgw support, I have created a fork to which I attempt to add this support. As of now, my first attempt at doing so is done. However, the code isn’t fully functional and needs fixing. Reading udpgw messages back seems not to work. Anyway, if anyone is interested, the link is https://github.com/mukswilly/go-tun2socks/tree/udpgw Fixes or pointers to fixes are welcome. Thanks

**Comment by mukswilly** [comment]
Just in case anybody is interested. I have a fork with fully functioning udpgw support at https://github.com/mukswilly/go-tun2socks

**Comment by ghost** [comment]
> Just in case anybody is interested. I have a fork with fully functioning udpgw support at https://github.com/mukswilly/go-tun2socks

link is broken
